### ISSUE TITLE
アトリビュートエラーに悩まされています。

### ISSUE THREAD

**Issue by BURI555** [Hiroshiba/nicolive-mastodon#1]
Pothon3.7入れて、mastdon.pyインストールして、config設定して動かしたところ、アトリビュートエラーが出ます。何が悪いのでしょうか？
C:\Users\user\Desktop\nicolive-mastodon-1.1.2>python run.py
running...
Traceback (most recent call last):
  File "run.py", line 126, in <module>
    runner.run()
  File "run.py", line 95, in run
    self.mastodon.local_stream(self)
AttributeError: 'Mastodon' object has no attribute 'local_stream'

**Comment by BURI555** [comment]
local_streamではなく、stream_localでした。95行を変える必要があります。
